create table if not exists public.posts (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 title text not null, price text, description text,
 images text[] not null default '{}',
 author_id uuid not null references auth.users(id) on delete cascade
);
alter table public.posts enable row level security;
create policy "public read" on public.posts for select to anon,authenticated using(true);
create policy "auth insert own" on public.posts for insert to authenticated with check(auth.uid()=author_id);
create policy "auth delete own" on public.posts for delete to authenticated using(auth.uid()=author_id);
insert into storage.buckets(id,name,public) values('vehicle-images','vehicle-images',true) on conflict(id) do update set public=true;
create policy "public images" on storage.objects for select to anon,authenticated using(bucket_id='vehicle-images');
create policy "auth upload own folder" on storage.objects for insert to authenticated with check(bucket_id='vehicle-images' and (storage.foldername(name))[1]=(select auth.uid()::text));
